### ISSUE TITLE
BLEURT returning scores less than zero

### ISSUE THREAD

**Issue by machelreid** [google-research/bleurt#1]
I'm not sure if this is supposed to happen or not, but when testing BLEURT on the test_data ( "Bud Powell was a legendary pianist.", etc...) I'm getting scores that are way below zero:

1. Here is my output for `bleurt/test_checkpoint`
```
0.9129246473312378
0.2755325436592102
-0.34470897912979126
-0.737292468547821
```

2. And my output for `bleurt-base-128`
```
1.003721833229065
0.5313903093338013
-1.489485502243042
-1.6975871324539185
```
Though I may be wrong, my understanding is that scores should be between 0 and 1. 
Thanks!

**Comment by tsellam** [comment]
Hi Machel, thanks for pointing this out!

This is actually not a bug, because BLEURT is not calibrated like BLEU. Instead, our model simulates the ratings of the [WMT Metrics shared task](http://www.statmt.org/wmt19/metrics-task.html), which are normalized per annotator. So you should expect negative scores.

It is difficult to assess what is a "bad" score and what is a "good" score, as this depends on the use case. Ideally, BLEURT should be used to compare systems, and we recommend against trying to interpret individual values.

That said, here are a few stats about the WMT data that may be used for reference, using `BLEURT-base-128`:
- The median translation in the WMT dataset has BLEURT score 0.13 (years 2015 to 2019)
- Translations with score < -0.26 are in the bottom 25%
- Translations with score > 0.4 are in the top 25%

The distribution of the BLEURT scores for the full WMT dataset is here:
![download](https://user-images.githubusercontent.com/6736052/81746705-f114a280-9474-11ea-9e19-89054b857565.png)

Note that the distribution is different for every checkpoint.  For `BLEURT-tiny-128`, the 25%, 50%, and 75% quantiles are 0.03, 0.29, and 0.49. The distribution is tighter, as shown here:

![download (3)](https://user-images.githubusercontent.com/6736052/81748206-6d0fea00-9477-11ea-8e7c-bcf0cb9b283b.png)

**Comment by machelreid** [comment]
Hi Thibault!

Thanks for clearing this up - the distribution graph is was pretty insightful. I think it would be a good idea to add some form this to the README (in case there are people who have the same misconceptions as me 😅  ).

Just to clarify, an appropriate use case of BLEURT would be when ranking different systems' performance on the same task?

Thanks!

**Comment by tsellam** [comment]
Hi Machel,

Thanks a lot for your feedback. I will update the README.

And yes, the best use of BLEURT is to compare systems on the same task. We recommend doing so because BLEURT scores are not binary ("good" vs. "bad"), they are almost always somewhere in between. So it is very hard to assess what is a "good" score without a baseline (as with BLEU).

The best use case: run BLEURT on a set sentences generated by system A, run it again on a set of sentences generated by system B, and compare the averages.

Hope this helps!

**Comment by ratthachat** [comment]
@tsellam The rating distribution plot is very insightful! I would support to put this information into README and also the 0, 10, 20, 30, ..., 90, 100 percentile statistical information for BLEURT-base ...

Moreover, BERTScore just got included in Huggingface NLP's metric (see News in https://github.com/Tiiiger/bert_score ). I think it will much widen to a lot more users if BLEURT also incorporates Huggingface ...

**Comment by bilalghanem** [comment]
Isn't possible to map the (-2 - 1) range to (0 - 100)? so I can get "understandable" numbers?

**Comment by tsellam** [comment]
Update: the latest BLEURT models returns values which are *mostly* between 0 and 1.

**Comment by bilalghanem** [comment]
> Update: the latest BLEURT models returns values which are _mostly_ between 0 and 1.

@tsellam how it has been done? could you please elaborate more?

**Comment by tsellam** [comment]
We rescaled the scores in our training data so that most of them fit within the [0,1] range, and clipped the ratings of the outliers. We also generated artificial positive examples with score 1, and artificial negative examples with score 0.

See [here](https://github.com/google-research/bleurt/blob/master/checkpoints.md) for more details.
