### ISSUE TITLE
How to use the checkpoints of BERT "warmed up" with synthetic ratings?

### ISSUE THREAD

**Issue by RoderickGu** [google-research/bleurt#12]
After I downloaded `bleurt` and successfully use the `test_checkpoint` or the fine-tuned checkpoint, I am thinking use the "warmed up" version. However, if I directly download the "warmed up" checkpoint and use it, it will show an error:
```
OSError: SavedModel file does not exist at: bleurt/bert-large-midtrained/bert-large//{saved_model.pbtxt|saved_model.pb}
```
After looking into the details, I found the files type under "warmed up" checkpoint is different than those under `test_checkpoint` or fine-tuned checkpoint.
Under fine-tuned checkpoint:
```
bert_config.json  bleurt_config.json  saved_model.pb  variables  vocab.txt
```

Under warmed up checkpoint:
```
bert_config.json  bert-large.data-00000-of-00001  bert-large.index  bert-large.meta  bleurt_config.json  vocab.txt
```
So how can we directly use the warmed up checkpoint for evaluation?

**Comment by tsellam** [comment]
Hi Roderick, thanks for your message! Indeed, the "warmed up" checkpoints are BERT checkpoints--not BLEURT.
You may use the following flags:
```
  -init_checkpoint=${BERT_DIR}/bert-large \
  -bert_config_file=${BERT_DIR}/bert_config.json \
  -vocab_file=${BERT_DIR}/vocab.txt \
```

**Comment by RoderickGu** [comment]
Sorry for not making this clear. I am using the provided python API as shown in the Read.ME:
```
from blurt import score
checkpoint = "bleurt/test_checkpoint"
references = ["This is a test."]
candidates = ["This is the test."]

scorer = score.BleurtScorer(checkpoint)
scores = scorer.score(references, candidates)
assert type(scores) == list and len(scores) == 1
print(scores)
```
It seems that `"bleurt/test_checkpoint"` is a BLEURT checkpoint, which can not be replaced by a BERT checkpoint. I want to use your metric on tasks other than WMT, therefore I need to use the warm-up version (after the second stage training) instead of the version that is fine-tuned on WMT. 

I wonder if there is a way to transfer your provided warmed up BERT version into BLEURT version? Thanks.

**Comment by tsellam** [comment]
Oh thanks for clarifying.

As you wrote, the warmed-up BERT models are not compatible with the BLEURT API code, because the underlying model has a different architecture (there are several regression / classification heads, one for each pre-training objective).
More generally, the warmed-up models were not designed to be used for inference. It is better to think of them as a starting point for training.

If you wish to evaluate a non-WMT metrics task, here are your options:
- you can still use the WMT checkpoints! So far, all our experiments showed that they transfer well to other domains. This should be your starting point.
- you can fine-tune BERT or BLEURT towards your own ratings with `finetune.py`. A few hundred examples should be enough. We recommend to initialize from BLEURT trained on WMT if you have a small set of ratings.
- use one of the metrics BLEURT was pre-trained on, say BLEU or [BERTscore](https://github.com/Tiiiger/bert_score), as the pre-training step merely learns to replicate them.

**Comment by RoderickGu** [comment]
Thanks for your detailed solution!
