### ISSUE TITLE
About the range of BLEURT scores.

### ISSUE THREAD

**Issue by ElliottYan** [google-research/bleurt#40]
Hi, 
I'm trying to evaluate my models with BLEURT, and I find contradictory descriptions in README now and the previous issues about how to interpret BLEURT scores.

As mentioned in README, "The currently recommended checkpoint BLEURT-20 generates scores which are roughly between 0 and 1 (sometimes less than 0, sometimes more than 1), where 0 indicates a random output and 1 a perfect one."

And as mentioned in this issue, the statistics of training corpus has a large portion of samples has negative values. 
https://github.com/google-research/bleurt/issues/1

If I understand correctly, the BLEURT scores can be bounded manually by myself if I can regard 0 as random and 1 as perfect. For instance, the negative values can be set to 0, and values more than 1 can be truncated to 1. 
Am I right?

**Comment by tsellam** [comment]
Hi ElliottYan,
Thanks for your message!
The issue you linked to refers to the previous version of BLEURT. We have made some improvements since then, most of the values should now be in the [0, 1] range.
You can still clip the values to [0,1] if necessary (as you describe) but you should not need to rescale them.
